volumes:
  clickhouse-db:

services:
  ch:
    image: bitnami/clickhouse:latest
    container_name: jelly_ch
    ports:
      - "0.0.0.0:8123:8123"  # Bind to all interfaces for external access
      - "0.0.0.0:9000:9000"  # Native protocol port
    environment:
      - CLICKHOUSE_ADMIN_USER=default
      - CLICKHOUSE_ADMIN_PASSWORD=Sakirs1234**  # Change this to your secure password
    volumes:
      - clickhouse-db:/bitnami/clickhouse
      - ./local/clickhouse/config.xml:/opt/bitnami/clickhouse/etc/conf.d/config.xml

  #  pg:
  #    image: postgres:15-alpine
  #    container_name: jelly_pg
  #    environment:
  #      POSTGRES_DB: 'postgres'
  #      POSTGRES_USER: 'postgres'
  #      POSTGRES_PASSWORD: 'postgres'
  #    ports:
  #      - '6432:5432'
  #    volumes:
  #      - subsquid-db:/var/lib/postgresql/data:delegated
