volumes:
  clickhouse-db:

services:
  ch:
    image: bitnami/clickhouse:latest
    container_name: jelly_ch
    ports:
      - '8123:8123'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - clickhouse-db:/bitnami/clickhouse
      - ./local/clickhouse/config.xml:/opt/bitnami/clickhouse/etc/conf.d/config.xml

  #  pg:
  #    image: postgres:15-alpine
  #    container_name: jelly_pg
  #    environment:
  #      POSTGRES_DB: 'postgres'
  #      POSTGRES_USER: 'postgres'
  #      POSTGRES_PASSWORD: 'postgres'
  #    ports:
  #      - '6432:5432'
  #    volumes:
  #      - subsquid-db:/var/lib/postgresql/data:delegated